In [1]:
import pandas as pd
from pathlib import Path

pd.set_option("display.max_columns", 200)
pd.set_option("display.width", 160)

In [5]:

from pathlib import Path

PROJECT_ROOT = Path.cwd().parents[1] 
DATA_DIR = PROJECT_ROOT / "data" / "gold"


df = pd.read_parquet(DATA_DIR / "gold_drivers.parquet")

In [6]:
df.head(10)

          DriverId         FullName  FirstName    LastName CountryCode         TeamName
0  kevin_magnussen  Kevin Magnussen      Kevin   Magnussen         DEN     Haas F1 Team
1           alonso  Fernando Alonso   Fernando      Alonso         ESP     Aston Martin
2          tsunoda     Yuki Tsunoda       Yuki     Tsunoda         JPN               RB
3            sainz     Carlos Sainz     Carlos       Sainz         ESP          Ferrari
4            albon  Alexander Albon  Alexander       Albon         THA         Williams
5   max_verstappen   Max Verstappen        Max  Verstappen         NED  Red Bull Racing
6           lawson      Liam Lawson       Liam      Lawson         NZL               RB
7             ocon     Esteban Ocon    Esteban        Ocon         FRA           Alpine
8           norris     Lando Norris      Lando      Norris         GBR          McLaren
9         sargeant   Logan Sargeant      Logan    Sargeant         USA         Williams

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25 entries, 0 to 24
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   DriverId     25 non-null     object
 1   FullName     25 non-null     object
 2   FirstName    25 non-null     object
 3   LastName     25 non-null     object
 4   CountryCode  25 non-null     object
 5   TeamName     25 non-null     object
dtypes: object(6)
memory usage: 1.3+ KB

In [8]:
df.columns.tolist()

['DriverId', 'FullName', 'FirstName', 'LastName', 'CountryCode', 'TeamName']

In [9]:
df.describe(include="all")

       DriverId        FullName FirstName LastName CountryCode      TeamName
count        25              25        25       25          25            25
unique       24              24        24       24          17            10
top     bearman  Oliver Bearman    Oliver  Bearman         GBR  Haas F1 Team
freq          2               2         2        2           5             3